
export const NotamAbbreviations: Record<string, string> = {
    "ABV": "ABOVE",
    "ACFT": "AIRCRAFT",
    "ACT": "ACTIVE",
    "AD": "AERODROME",
    "ADJ": "ADJACENT",
    "ALT": "ALTITUDE",
    "ALTN": "ALTERNATE",
    "AMD": "AMEND",
    "APCH": "APPROACH",
    "APN": "APRON",
    "ARR": "ARRIVAL",
    "ASPH": "ASPHALT",
    "AUTH": "AUTHORIZED",
    "AVBL": "AVAILABLE",
    "AWY": "AIRWAY",
    "AZM": "AZIMUTH",
    "BCN": "BEACON",
    "BFR": "BEFORE",
    "BLW": "BELOW",
    "BND": "BOUND",
    "BRG": "BEARING",
    "BTN": "BETWEEN",
    "CAT": "CATEGORY",
    "CHG": "CHANGE",
    "CIG": "CEILING",
    "CK": "CHECK",
    "CL": "CENTERLINE",
    "CLSD": "CLOSED",
    "CMB": "CLIMB",
    "CMD": "COMMAND",
    "CNL": "CANCEL",
    "COM": "COMMUNICATIONS",
    "CONC": "CONCRETE",
    "COND": "CONDITION",
    "CONST": "CONSTRUCTION",
    "COORD": "COORDINATES",
    "CTC": "CONTACT",
    "CTL": "CONTROL",
    "DALGT": "DAYLIGHT",
    "DECR": "DECREASE",
    "DEG": "DEGREES",
    "DEP": "DEPARTURE",
    "DES": "DESCEND",
    "DIST": "DISTANCE",
    "DLA": "DELAY",
    "DLY": "DAILY",
    "DME": "DISTANCE MEASURING EQUIPMENT",
    "DUR": "DURATION",
    "EB": "EASTBOUND",
    "EBO": "EASTBOUND",
    "EFF": "EFFECTIVE",
    "ELEV": "ELEVATION",
    "ENG": "ENGINE",
    "ENRT": "EN ROUTE",
    "ENTR": "ENTIRE",
    "EQUIP": "EQUIPMENT",
    "EST": "ESTIMATED",
    "EXC": "EXCEPT",
    "FAC": "FACILITY",
    "FAF": "FINAL APPROACH FIX",
    "FAN MKR": "FAN MARKER",
    "FDC": "FLIGHT DATA CENTER",
    "FM": "FROM",
    "FREQ": "FREQUENCY",
    "FRI": "FRIDAY",
    "FRT": "FRONT",
    "FT": "FEET",
    "GND": "GROUND",
    "GP": "GLIDE PATH",
    // "GPS": "GLOBAL POSITIONING SYSTEM",
    "GRVL": "GRAVEL",
    "HGT": "HEIGHT",
    "HIWAS": "HAZARDOUS INFLIGHT WEATHER ADVISORY SERVICE",
    "HOL": "HOLIDAY",
    "HR": "HOUR",
    "HWY": "HIGHWAY",
    "IAP": "INSTRUMENT APPROACH PROCEDURE",
    "IDENT": "IDENTIFICATION",
    // "ILS": "INSTRUMENT LANDING SYSTEM",
    "IM": "INNER MARKER",
    "INBD": "INBOUND",
    "INDEF": "INDEFINITELY",
    "INFO": "INFORMATION",
    "INOP": "INOPERATIVE",
    "INSTR": "INSTRUMENT",
    "INT": "INTERSECTION",
    "INTL": "INTERNATIONAL",
    "INTST": "INTENSITY",
    "IR": "ICE ON RUNWAY",
    "LAT": "LATITUDE",
    "LB": "POUND",
    "LGT": "LIGHT",
    "LGTD": "LIGHTED",
    "LOC": "LOCALIZER",
    "LONG": "LONGITUDE",
    "MAINT": "MAINTENANCE",
    "MAX": "MAXIMUM",
    "MBST": "MICROBURST",
    "MDA": "MINIMUM DESCENT ALTITUDE",
    "MEA": "MINIMUM EN ROUTE ALTITUDE",
    "MED": "MEDIUM",
    "MIN": "MINIMUM",
    "MIRL": "MEDIUM INTENSITY RUNWAY LIGHTS",
    "MKR": "MARKER",
    "MM": "MIDDLE MARKER",
    "MNM": "MINIMUM",
    "MOCA": "MINIMUM OBSTRUCTION CLEARANCE ALTITUDE",
    "MON": "MONDAY",
    "MRA": "MINIMUM RECEPTION ALTITUDE",
    "MSA": "MINIMUM SAFE ALTITUDE",
    "MSL": "MEAN SEA LEVEL",
    "N": "NORTH",
    "NA": "NOT AUTHORIZED",
    "NAV": "NAVIGATION",
    "NB": "NORTHBOUND",
    "NBO": "NORTHBOUND",
    "NDB": "NON-DIRECTIONAL BEACON",
    "NE": "NORTHEAST",
    "NGT": "NIGHT",
    "NM": "NAUTICAL MILE",
    "NMR": "NAUTICAL MILE RADIUS",
    "NONSTD": "NON-STANDARD",
    "NOTAM": "NOTICE TO AIRMEN",
    "NW": "NORTHWEST",
    "OBSC": "OBSCURED",
    "OBST": "OBSTRUCTION",
    "OM": "OUTER MARKER",
    "OPR": "OPERATE",
    "OPS": "OPERATIONS",
    "ORIG": "ORIGINAL",
    "OTS": "OUT OF SERVICE",
    "OVR": "OVER",
    "PAEW": "PERSONNEL AND EQUIPMENT WORKING",
    "PAR": "PRECISION APPROACH RADAR",
    "PERM": "PERMANENT",
    "PJE": "PARACHUTE JUMPING EXERCISE",
    "PLA": "PRACTICE LOW APPROACH",
    "PLW": "PLOW",
    "PN": "PRIOR NOTICE",
    "PPR": "PRIOR PERMISSION REQUIRED",
    "PRN": "PSUEDO RANDOM NOISE",
    "PROC": "PROCEDURE",
    "PROP": "PROPELLER",
    "PSR": "PACKED SNOW ON RUNWAY",
    "PTN": "PROCEDURE TURN",
    "PVT": "PRIVATE",
    "RAIL": "RUNWAY ALIGNMENT INDICATOR LETTERS",
    "RCAG": "REMOTE COMMUNICATIONS AIR/GROUND FACILITY",
    "RCL": "RUNWAY CENTERLINE",
    "RCLL": "RUNWAY CENTERLINE LIGHTS",
    "RCO": "REMOTE COMMUNICATIONS OUTLET",
    "REC": "RECEIVE",
    "REIL": "RUNWAY END IDENTIFIER LIGHTS",
    "RELCT": "RELOCATED",
    "REP": "REPORT",
    "RLLS": "RUNWAY LEAD-IN LIGHTING SYSTEM",
    "RMK": "REMARK",
    // "RNAV": "AREA NAVIGATION",
    "RPLC": "REPLACE",
    "RQRD": "REQUIRED",
    "RRL": "RUNWAY REMAINING LIGHTS",
    "RTE": "ROUTE",
    "RTR": "REMOTE TRANSMITTER/RECEIVER",
    "RTS": "RETURN TO SERVICE",
    "RUF": "ROUGH",
    "RVR": "RUNWAY VISUAL RANGE",
    "RVRM": "RVR MIDPOINT",
    "RVRR": "RVR ROLLOUT",
    "RVRT": "RVR TOUCHDOWN",
    "RWY": "RUNWAY",
    "SAT": "SATURDAY",
    "SB": "SOUTHBOUND",
    "SBO": "SOUTHBOUND",
    "SE": "SOUTHEAST",
    "SEC": "SECONDS",
    "SFC": "SURFACE",
    "SI": "STRAIGHT-IN APPROACH",
    "SID": "STANDARD INSTRUMENT DEPARTURE",
    "SKED": "SCHEDULED",
    "SLR": "SLUSH ON RUNWAY",
    "SN": "SNOW",
    "SNBNK": "SNOWBANK",
    "SPD": "SPEED",
    "SR": "SUNRISE",
    "SS": "SUNSET",
    "SSR": "SECONDARY SURVEILLANCE RADAR",
    "STA": "STRAIGHT-IN APPROACH",
    "STAR": "STANDARD TERMINAL ARRIVAL",
    "STD": "STANDARD",
    "SUN": "SUNDAY",
    "SVC": "SERVICE",
    "SW": "SOUTHWEST",
    "T": "TEMPERATURE",
    "TACAN": "TACTICAL AIR NAVIGATION",
    "TDZ": "TOUCHDOWN ZONE",
    "TDZ LGT": "TOUCHDOWN ZONE LIGHT",
    "TEMPO": "TEMPORARY",
    "TFC": "TRAFFIC",
    "TFR": "TEMPORARY FLIGHT RESTRICTION",
    "THR": "THRESHOLD",
    "THU": "THURSDAY",
    "TIL": "UNTIL",
    "TKOF": "TAKEOFF",
    "TMPRY": "TEMPORARY",
    "TRML": "TERMINAL",
    "TRSN": "TRANSITION",
    "TS": "THUNDERSTORM",
    "TUE": "TUESDAY",
    "TWR": "TOWER",
    "TWY": "TAXIWAY",
    "U/S": "UNSERVICEABLE",
    "UFN": "UNTIL FURTHER NOTICE",
    "UNAVBL": "UNAVAILABLE",
    "UNLGTD": "UNLIGHTED",
    "UNMNT": "UNMONITORED",
    "UNREL": "UNRELIABLE",
    "UNUSBL": "UNUSABLE",
    "VASI": "VISUAL APPROACH SLOPE INDICATOR",
    "VDP": "VISUAL DESCENT POINT",
    "VIA": "VIA",
    "VICE": "INSTEAD/VERSUS",
    "VIS": "VISIBILITY",
    "VMC": "VISUAL METEOROLOGICAL CONDITIONS",
    "VOL": "VOLUME",
    "WB": "WESTBOUND",
    "WBO": "WESTBOUND",
    "WED": "WEDNESDAY",
    "WEF": "WITH EFFECT FROM",
    "WI": "WITHIN",
    "WIE": "WITH IMMEDIATE EFFECT",
    "WIP": "WORK IN PROGRESS",
    "WKDAYS": "WEEKDAYS",
    "WKEND": "WEEKEND",
    "WND": "WIND",
    "WPT": "WAYPOINT",
    "WSTCH": "WASATCH",
    "WX": "WEATHER",
};

export class NotamDecoder {
    public static decode(text: string): string {
        if (!text) return "";

        let decoded = text;

        // Sort keys by length descending to handle containment (e.g. U/S before S)
        const sortedKeys = Object.keys(NotamAbbreviations).sort((a, b) => b.length - a.length);

        for (const abbr of sortedKeys) {
            const full = NotamAbbreviations[abbr];
            // Match whole word, case insensitive
            // Escape special chars in abbr if any (like / in U/S)
            const escapedAbbr = abbr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

            const regex = new RegExp(`\\b${escapedAbbr}\\b`, 'gi');
            decoded = decoded.replace(regex, full);
        }

        return decoded;
    }
}
