-- Generated by the database client.
CREATE TABLE sheets (
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id integer NOT NULL,
    "data" text,
    name varchar(255),
    version integer,
    description varchar(255) DEFAULT NULL::character varying,
    creation_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    pages integer,
    thumbnail varchar(255),
    thumbhash character(64),
    format varchar(16) DEFAULT 'kneeboard'::character varying,
    PRIMARY KEY (id),
    CONSTRAINT pages_user_id_fkey FOREIGN key (user_id) REFERENCES users (id)
);

-- Generated by the database client.
CREATE TABLE feedback (
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    time date NOT NULL DEFAULT CURRENT_DATE,
    version varchar(64),
    text varchar(1024),
    user_id integer,
    contact boolean DEFAULT false,
    PRIMARY KEY (id),
    CONSTRAINT feedback_user_id_fkey FOREIGN key (user_id) REFERENCES users (id)
);
-- Generated by the database client.
CREATE TABLE airports (
    code varchar(5),
    "data" text,
    id SERIAL NOT NULL,
    version integer DEFAULT 0,
    creatorid integer,
    sketch varchar(255),
    "source" airportsource DEFAULT 'adip'::airportsource,
    PRIMARY KEY (id)
);
-- Generated by the database client.
CREATE TABLE users (
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    sha256 varchar(64) NOT NULL,
    version integer NOT NULL,
    "data" varchar(1024),
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    account_type varchar(8),
    customer_id varchar(255),
    print_credit integer NOT NULL DEFAULT 0,
    max_templates integer,
    max_pages integer DEFAULT 4,
    eula integer DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX users_sha256_key ON public.users USING btree (sha256);

CREATE UNIQUE INDEX users_sha256_idx ON public.users USING btree (sha256);
## 12/19/2025 Add a new airportsource named 'skyvector' Dev + Prod
ALTER TYPE airportsource ADD VALUE 'skyvector';

## 12/28/2025 Dev + Prod
CREATE TABLE skyvector (
    id SERIAL NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    code varchar(5),
    "data" text,
    PRIMARY KEY (id)
);

## 12/15/2025 Dev + Prod
CREATE TYPE airportsource AS ENUM ('adip', 'user');

## 09/18/2025 Dev + Prod
ALTER TYPE usagetype ADD VALUE 'refill'
ALTER TYPE usagetype ADD VALUE 'eula'

## 04/19/2025 Dev + Prod
ALTER TYPE usagetype ADD VALUE 'save'

## 04/19/2025 Dev + Prod
CREATE TABLE thumbnails (
    id SERIAL PRIMARY KEY,
    template_id integer,
    thumbhash VARCHAR(64),
    png_data BYTEA,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

## 03/15/2025 Dev + Prod
CREATE UNIQUE INDEX ON users (sha256)

-- Generated by the database client.
CREATE TABLE adip (
    id SERIAL NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    code varchar(5),
    "data" text,
    PRIMARY KEY (id)
);
-- Generated by the database client.
CREATE TABLE health_checks (
    id SERIAL NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    "data" varchar(1024),
    failures integer DEFAULT 0,
    PRIMARY KEY (id)
);
-- Generated by the database client.
CREATE TABLE metrics (
    id SERIAL NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    "data" varchar(1024),
    PRIMARY KEY (id)
);
-- Generated by the database client.
CREATE TABLE publications (
    id SERIAL NOT NULL,
    sheetid integer,
    code varchar(3),
    PRIMARY KEY (id)
);
-- Generated by the database client.
CREATE TABLE sheets (
    id SERIAL NOT NULL,
    user_id integer NOT NULL,
    "data" text,
    name varchar(255),
    version integer,
    PRIMARY KEY (id),
    CONSTRAINT pages_user_id_fkey FOREIGN key (user_id) REFERENCES users (id)
);
-- Generated by the database client.
CREATE TABLE unknowns (
    id SERIAL NOT NULL,
    code varchar(255),
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX unknowns_code_key ON unknowns USING btree ("code");