-- Generated by the database client.
CREATE TABLE airports(
    code varchar(5),
    "data" text,
    id SERIAL NOT NULL,
    version integer DEFAULT 0,
    creatorid integer,
    sketch varchar(255),
    "source" airportsource DEFAULT 'adip'::airportsource,
    PRIMARY KEY(id)
);