-- Generated by the database client.
CREATE TABLE feedback(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    time date NOT NULL DEFAULT CURRENT_DATE,
    version varchar(64),
    text varchar(1024),
    user_id integer,
    contact boolean DEFAULT false,
    PRIMARY KEY(id),
    CONSTRAINT feedback_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);