-- Generated by the database client.
CREATE TABLE housekeeping(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    "data" JSONB,
    failed integer DEFAULT 0,
    passed integer DEFAULT 0,
    skipped integer DEFAULT 0,
    PRIMARY KEY(id)
);
