-- Generated by the database client.
CREATE TABLE usage(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    user_id integer,
    "data" text,
    usage_type usagetype,
    PRIMARY KEY(id),
    CONSTRAINT prints_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);