-- Generated by the database client.
CREATE TABLE adip(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    code varchar(5),
    "data" text,
    PRIMARY KEY(id)
);