-- Generated by the database client.
CREATE TABLE health_checks(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    "data" varchar(1024),
    failures integer DEFAULT 0,
    PRIMARY KEY(id)
);