-- Generated by the database client.
CREATE TABLE metrics(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    "data" varchar(1024),
    PRIMARY KEY(id)
);