-- Generated by the database client.
CREATE TABLE publications(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    sheetid integer,
    code varchar(3),
    active boolean DEFAULT true,
    PRIMARY KEY(id)
);