-- Generated by the database client.
CREATE TABLE "sessions-stale"(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    user_id integer,
    PRIMARY KEY(id),
    CONSTRAINT sessions_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);