-- Generated by the database client.
CREATE TABLE unknowns(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    code varchar(255),
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX unknowns_code_key ON unknowns USING btree ("code");