-- Generated by the database client.
CREATE TABLE users(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
    sha256 varchar(64) NOT NULL,
    version integer NOT NULL,
    "data" varchar(1024),
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX users_sha256_key ON users USING btree ("sha256");