-- Generated by the database client.
CREATE TABLE adip(
    id SERIAL NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    code varchar(5),
    "data" text,
    PRIMARY KEY(id)
);
-- Generated by the database client.
CREATE TABLE airports(
    code varchar(5),
    "data" varchar(4096),
    id SERIAL NOT NULL,
    version integer DEFAULT 0,
    creatorid integer,
    PRIMARY KEY(id)
);
-- Generated by the database client.
CREATE TABLE feedback(
    id SERIAL NOT NULL,
    time date NOT NULL DEFAULT CURRENT_DATE,
    version varchar(64),
    text varchar(1024),
    user256 varchar(64) DEFAULT NULL::character varying,
    PRIMARY KEY(id)
);
-- Generated by the database client.
CREATE TABLE health_checks(
    id SERIAL NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    "data" varchar(1024),
    failures integer DEFAULT 0,
    PRIMARY KEY(id)
);
-- Generated by the database client.
CREATE TABLE metrics(
    id SERIAL NOT NULL,
    create_time timestamp without time zone DEFAULT now(),
    "data" varchar(1024),
    PRIMARY KEY(id)
);
-- Generated by the database client.
CREATE TABLE publications(
    id SERIAL NOT NULL,
    sheetid integer,
    code varchar(3),
    PRIMARY KEY(id)
);
-- Generated by the database client.
CREATE TABLE sheets(
    id SERIAL NOT NULL,
    user_id integer NOT NULL,
    "data" text,
    name varchar(255),
    version integer,
    PRIMARY KEY(id),
    CONSTRAINT pages_user_id_fkey FOREIGN key(user_id) REFERENCES users(id)
);
-- Generated by the database client.
CREATE TABLE unknowns(
    id SERIAL NOT NULL,
    code varchar(255),
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX unknowns_code_key ON unknowns USING btree ("code");
-- Generated by the database client.
CREATE TABLE users(
    id SERIAL NOT NULL,
    sha256 varchar(64) NOT NULL,
    version integer NOT NULL,
    "data" varchar(1024),
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX users_sha256_key ON users USING btree ("sha256");


## 03/22/2025 Dev
## 03/23/2025 Prod
ALTER TABLE airports ADD COLUMN sketch varchar(255);

## 03/15/2025 Dev[x] Prod[x]
CREATE UNIQUE INDEX ON users (sha256)